noun1 = input("First noun: ")
verb1 = input("First verb: ")
noun2 = input("Second verb: ")
verb2 = input("Second verb: ")
adjective1 = input("First adjective: ")
place1 = input("First place: ")
noun3 = input("Third noun: ")
verb3 = input("Third verb: ")
adjective2= input("Second adjective= ")
place2 = input("Second place: ")
print(noun1 + verb1 + noun2 + "and" + verb2 + adjective1 + "went" + place1 + "." + "Then" + noun3 + verb3 + adjective2 + "fly" + "in" + place2 + ".")